/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kcs.main;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author ciclot
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogComensales = new javax.swing.JDialog();
        jPanelModal = new javax.swing.JPanel();
        jPanelBarra2 = new javax.swing.JPanel();
        jLabelNumCom = new javax.swing.JLabel();
        jPanelMenu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaMenu = new javax.swing.JTextArea();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelC1 = new javax.swing.JLabel();
        jLabelC2 = new javax.swing.JLabel();
        jLabelC3 = new javax.swing.JLabel();
        jLabelC4 = new javax.swing.JLabel();
        jLabelC5 = new javax.swing.JLabel();
        jTextFieldC5 = new javax.swing.JTextField();
        jTextFieldC3 = new javax.swing.JTextField();
        jTextFieldC4 = new javax.swing.JTextField();
        jTextFieldC1 = new javax.swing.JTextField();
        jTextFieldC2 = new javax.swing.JTextField();
        jPanelBorde = new javax.swing.JPanel();
        jPanelContenedor2 = new javax.swing.JPanel();
        jPanelBarra3 = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelNomRes = new javax.swing.JLabel();
        jPanelTextBox = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jPanelComensales = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanelReserva = new javax.swing.JPanel();
        jRadioButtonComida = new javax.swing.JRadioButton();
        jRadioButtonCena = new javax.swing.JRadioButton();
        jComboBoxComida = new javax.swing.JComboBox<>();
        jComboBoxCena = new javax.swing.JComboBox<>();
        jLabelComensales = new javax.swing.JLabel();
        jButtonReservar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jPanelTextBox1 = new javax.swing.JPanel();
        jCalendarFecha = new com.toedter.calendar.JCalendar();

        jDialogComensales.setBackground(new java.awt.Color(64, 64, 64));
        jDialogComensales.setForeground(java.awt.Color.cyan);
        jDialogComensales.setMinimumSize(new java.awt.Dimension(575, 655));
        jDialogComensales.setModal(true);

        jPanelModal.setBackground(new java.awt.Color(64, 64, 64));
        jPanelModal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 180, 180), 3, true));
        jPanelModal.setMinimumSize(new java.awt.Dimension(556, 600));
        jPanelModal.setPreferredSize(new java.awt.Dimension(556, 580));

        jPanelBarra2.setBackground(new java.awt.Color(38, 38, 38));
        jPanelBarra2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        jPanelBarra2.setMinimumSize(new java.awt.Dimension(550, 71));
        jPanelBarra2.setPreferredSize(new java.awt.Dimension(550, 71));

        jLabelNumCom.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNumCom.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabelNumCom.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumCom.setText("Número de comensales seleccionado: N - Seleccione los platos para cada comensal (Máximo 4)");

        javax.swing.GroupLayout jPanelBarra2Layout = new javax.swing.GroupLayout(jPanelBarra2);
        jPanelBarra2.setLayout(jPanelBarra2Layout);
        jPanelBarra2Layout.setHorizontalGroup(
            jPanelBarra2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanelBarra2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBarra2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelNumCom)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelBarra2Layout.setVerticalGroup(
            jPanelBarra2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
            .addGroup(jPanelBarra2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBarra2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabelNumCom)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelMenu.setBackground(new java.awt.Color(80, 80, 80));
        jPanelMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 180, 180), 1, true));

        jTextAreaMenu.setColumns(20);
        jTextAreaMenu.setFont(new java.awt.Font("Arial", 0, 7)); // NOI18N
        jTextAreaMenu.setRows(5);
        jTextAreaMenu.setFocusable(false);
        jScrollPane1.setViewportView(jTextAreaMenu);

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );

        jButtonAceptar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAceptar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonAceptar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickButtonAceptar(evt);
            }
        });

        jButtonCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickButtonCancelar(evt);
            }
        });

        jLabelC1.setBackground(new java.awt.Color(80, 80, 80));
        jLabelC1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelC1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelC1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelC1.setText("1");
        jLabelC1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        jLabelC1.setEnabled(false);
        jLabelC1.setMinimumSize(new java.awt.Dimension(36, 36));
        jLabelC1.setOpaque(true);
        jLabelC1.setPreferredSize(new java.awt.Dimension(34, 34));

        jLabelC2.setBackground(new java.awt.Color(80, 80, 80));
        jLabelC2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelC2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelC2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelC2.setText("2");
        jLabelC2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        jLabelC2.setEnabled(false);
        jLabelC2.setMinimumSize(new java.awt.Dimension(36, 36));
        jLabelC2.setOpaque(true);
        jLabelC2.setPreferredSize(new java.awt.Dimension(34, 34));

        jLabelC3.setBackground(new java.awt.Color(80, 80, 80));
        jLabelC3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelC3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelC3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelC3.setText("3");
        jLabelC3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        jLabelC3.setEnabled(false);
        jLabelC3.setMinimumSize(new java.awt.Dimension(36, 36));
        jLabelC3.setOpaque(true);
        jLabelC3.setPreferredSize(new java.awt.Dimension(34, 34));

        jLabelC4.setBackground(new java.awt.Color(80, 80, 80));
        jLabelC4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelC4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelC4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelC4.setText("4");
        jLabelC4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        jLabelC4.setEnabled(false);
        jLabelC4.setMinimumSize(new java.awt.Dimension(36, 36));
        jLabelC4.setOpaque(true);
        jLabelC4.setPreferredSize(new java.awt.Dimension(34, 34));

        jLabelC5.setBackground(new java.awt.Color(80, 80, 80));
        jLabelC5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelC5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelC5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelC5.setText("5");
        jLabelC5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        jLabelC5.setEnabled(false);
        jLabelC5.setMinimumSize(new java.awt.Dimension(36, 36));
        jLabelC5.setOpaque(true);
        jLabelC5.setPreferredSize(new java.awt.Dimension(34, 34));

        jTextFieldC5.setEnabled(false);

        jTextFieldC3.setEnabled(false);

        jTextFieldC4.setEnabled(false);

        jTextFieldC1.setEnabled(false);

        jTextFieldC2.setEnabled(false);

        javax.swing.GroupLayout jPanelModalLayout = new javax.swing.GroupLayout(jPanelModal);
        jPanelModal.setLayout(jPanelModalLayout);
        jPanelModalLayout.setHorizontalGroup(
            jPanelModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBarra2, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
            .addGroup(jPanelModalLayout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jButtonCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelModalLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanelModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelC4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelC5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldC5, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldC3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldC4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldC1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldC2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        jPanelModalLayout.setVerticalGroup(
            jPanelModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModalLayout.createSequentialGroup()
                .addComponent(jPanelBarra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelModalLayout.createSequentialGroup()
                        .addGroup(jPanelModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldC1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldC2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldC3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelC4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldC4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelC5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldC5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(47, 47, 47)
                .addGroup(jPanelModalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogComensalesLayout = new javax.swing.GroupLayout(jDialogComensales.getContentPane());
        jDialogComensales.getContentPane().setLayout(jDialogComensalesLayout);
        jDialogComensalesLayout.setHorizontalGroup(
            jDialogComensalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelModal, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );
        jDialogComensalesLayout.setVerticalGroup(
            jDialogComensalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelModal, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(180, 180, 180));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(1012, 517));

        jPanelBorde.setBackground(new java.awt.Color(180, 180, 180));
        jPanelBorde.setPreferredSize(new java.awt.Dimension(1010, 560));

        jPanelContenedor2.setBackground(new java.awt.Color(64, 64, 64));
        jPanelContenedor2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(120, 120, 120)));
        jPanelContenedor2.setPreferredSize(new java.awt.Dimension(1000, 550));

        jPanelBarra3.setBackground(new java.awt.Color(38, 38, 38));
        jPanelBarra3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(120, 120, 120)));
        jPanelBarra3.setPreferredSize(new java.awt.Dimension(1000, 80));

        jLabelLogo.setIcon(new javax.swing.ImageIcon("E:\\DAM\\Recursos\\SF-LogoEIE.png")); // NOI18N

        jLabelNomRes.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelNomRes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomRes.setText("Restaurante");

        javax.swing.GroupLayout jPanelBarra3Layout = new javax.swing.GroupLayout(jPanelBarra3);
        jPanelBarra3.setLayout(jPanelBarra3Layout);
        jPanelBarra3Layout.setHorizontalGroup(
            jPanelBarra3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBarra3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 747, Short.MAX_VALUE)
                .addComponent(jLabelNomRes)
                .addGap(31, 31, 31))
        );
        jPanelBarra3Layout.setVerticalGroup(
            jPanelBarra3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanelBarra3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelNomRes)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanelTextBox.setBackground(new java.awt.Color(80, 80, 80));
        jPanelTextBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 180, 180), 1, true));

        jLabelNombre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre");

        jLabelTelefono.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelTelefono.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTelefono.setText("Teléfono");

        javax.swing.GroupLayout jPanelTextBoxLayout = new javax.swing.GroupLayout(jPanelTextBox);
        jPanelTextBox.setLayout(jPanelTextBoxLayout);
        jPanelTextBoxLayout.setHorizontalGroup(
            jPanelTextBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTextBoxLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelTextBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTelefono)
                    .addComponent(jLabelNombre))
                .addGap(18, 18, 18)
                .addGroup(jPanelTextBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addComponent(jTextFieldNombre))
                .addContainerGap())
        );
        jPanelTextBoxLayout.setVerticalGroup(
            jPanelTextBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTextBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTextBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanelTextBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelefono))
                .addContainerGap())
        );

        jPanelComensales.setBackground(new java.awt.Color(80, 80, 80));
        jPanelComensales.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 180, 180), 1, true));
        jPanelComensales.setLayout(new java.awt.GridLayout(3, 4));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("1");
        jButton1.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickComensal1(evt);
            }
        });
        jPanelComensales.add(jButton1);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("2");
        jButton2.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickComensal2(evt);
            }
        });
        jPanelComensales.add(jButton2);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("3");
        jButton3.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickComensal3(evt);
            }
        });
        jPanelComensales.add(jButton3);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("4");
        jButton4.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickComensal4(evt);
            }
        });
        jPanelComensales.add(jButton4);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("5");
        jButton5.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickComensal5(evt);
            }
        });
        jPanelComensales.add(jButton5);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("6");
        jButton6.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickComensal6(evt);
            }
        });
        jPanelComensales.add(jButton6);

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setText("7");
        jButton7.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickComensal7(evt);
            }
        });
        jPanelComensales.add(jButton7);

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 0, 0));
        jButton8.setText("8");
        jButton8.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickComensal8(evt);
            }
        });
        jPanelComensales.add(jButton8);

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 0, 0));
        jButton9.setText("9");
        jButton9.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickComensal9(evt);
            }
        });
        jPanelComensales.add(jButton9);

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 0, 0));
        jButton10.setText("10");
        jButton10.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickComensal10(evt);
            }
        });
        jPanelComensales.add(jButton10);

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton11.setForeground(new java.awt.Color(0, 0, 0));
        jButton11.setText("11");
        jButton11.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickComensal11(evt);
            }
        });
        jPanelComensales.add(jButton11);

        jButton12.setBackground(new java.awt.Color(255, 255, 255));
        jButton12.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton12.setForeground(new java.awt.Color(0, 0, 0));
        jButton12.setText("12");
        jButton12.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickComensal12(evt);
            }
        });
        jPanelComensales.add(jButton12);

        jPanelReserva.setBackground(new java.awt.Color(80, 80, 80));
        jPanelReserva.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 180, 180), 1, true));
        jPanelReserva.setPreferredSize(new java.awt.Dimension(392, 91));

        jRadioButtonComida.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jRadioButtonComida.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonComida.setText("Comida");
        jRadioButtonComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioComidaClick(evt);
            }
        });

        jRadioButtonCena.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jRadioButtonCena.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonCena.setText("Cena");
        jRadioButtonCena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCenaClick(evt);
            }
        });

        jComboBoxComida.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboBoxComida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione hora", "13:30", "13:45", "14:30", "15:00", "15:15" }));
        jComboBoxComida.setEnabled(false);

        jComboBoxCena.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboBoxCena.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione hora", "20:00", "20:45", "21:30", "22:15" }));
        jComboBoxCena.setEnabled(false);

        javax.swing.GroupLayout jPanelReservaLayout = new javax.swing.GroupLayout(jPanelReserva);
        jPanelReserva.setLayout(jPanelReservaLayout);
        jPanelReservaLayout.setHorizontalGroup(
            jPanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReservaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonCena)
                    .addComponent(jRadioButtonComida))
                .addGap(18, 18, 18)
                .addGroup(jPanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxComida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxCena, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelReservaLayout.setVerticalGroup(
            jPanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReservaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonComida)
                    .addComponent(jComboBoxComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonCena)
                    .addComponent(jComboBoxCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelComensales.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelComensales.setForeground(new java.awt.Color(255, 255, 255));
        jLabelComensales.setText("Número de comensales");

        jButtonReservar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonReservar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonReservar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonReservar.setText("Reservar");
        jButtonReservar.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickButtonReservar(evt);
            }
        });

        jButtonBorrar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBorrar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonBorrar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBorrar.setText("Borrar");
        jButtonBorrar.setPreferredSize(new java.awt.Dimension(100, 100));
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickButtonBorrar(evt);
            }
        });

        jPanelTextBox1.setBackground(new java.awt.Color(80, 80, 80));
        jPanelTextBox1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 180, 180), 1, true));

        jCalendarFecha.setTodayButtonVisible(true);
        jCalendarFecha.setWeekOfYearVisible(false);

        javax.swing.GroupLayout jPanelTextBox1Layout = new javax.swing.GroupLayout(jPanelTextBox1);
        jPanelTextBox1.setLayout(jPanelTextBox1Layout);
        jPanelTextBox1Layout.setHorizontalGroup(
            jPanelTextBox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTextBox1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCalendarFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTextBox1Layout.setVerticalGroup(
            jPanelTextBox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTextBox1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCalendarFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelContenedor2Layout = new javax.swing.GroupLayout(jPanelContenedor2);
        jPanelContenedor2.setLayout(jPanelContenedor2Layout);
        jPanelContenedor2Layout.setHorizontalGroup(
            jPanelContenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedor2Layout.createSequentialGroup()
                .addComponent(jPanelBarra3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenedor2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanelContenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContenedor2Layout.createSequentialGroup()
                        .addComponent(jPanelTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelContenedor2Layout.createSequentialGroup()
                        .addGroup(jPanelContenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelComensales)
                            .addComponent(jPanelReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelComensales, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenedor2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelTextBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanelContenedor2Layout.setVerticalGroup(
            jPanelContenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedor2Layout.createSequentialGroup()
                .addComponent(jPanelBarra3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelContenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelContenedor2Layout.createSequentialGroup()
                        .addComponent(jPanelTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelComensales)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelComensales, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelTextBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelContenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelBordeLayout = new javax.swing.GroupLayout(jPanelBorde);
        jPanelBorde.setLayout(jPanelBordeLayout);
        jPanelBordeLayout.setHorizontalGroup(
            jPanelBordeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBordeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelContenedor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBordeLayout.setVerticalGroup(
            jPanelBordeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBordeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelContenedor2, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBorde, javax.swing.GroupLayout.PREFERRED_SIZE, 1012, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBorde, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables
    private int numComensales = -1;
    private String[] arrayC1;
    private String[] arrayC2;
    private String[] arrayC3;
    private String[] arrayC4;
    private String[] arrayC5;
    private int diaSem;
    private int diaMes;
    private int mes;
    private int any;

    // Eventos
    private void clickComensal1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickComensal1
        // Borrar datos comensal
        borrarComensales();

        // Asignar número de comensales
        numComensales = 1;

        // Mostrar diálogo modal
        llamarModal(numComensales);
    }//GEN-LAST:event_clickComensal1

    private void clickComensal2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickComensal2
        // Borrar datos comensal
        borrarComensales();

        // Asignar número de comensales
        numComensales = 2;

        // Mostrar diálogo modal
        llamarModal(numComensales);
    }//GEN-LAST:event_clickComensal2

    private void clickComensal3(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickComensal3
        // Borrar datos comensal
        borrarComensales();

        // Asignar número de comensales
        numComensales = 3;

        // Mostrar diálogo modal
        llamarModal(numComensales);
    }//GEN-LAST:event_clickComensal3

    private void clickComensal4(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickComensal4
        // Borrar datos comensal
        borrarComensales();

        // Asignar número de comensales
        numComensales = 4;

        // Mostrar diálogo modal
        llamarModal(numComensales);
    }//GEN-LAST:event_clickComensal4

    private void clickComensal5(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickComensal5
        // Borrar datos comensal
        borrarComensales();

        // Asignar número de comensales
        numComensales = 5;

        // Mostrar diálogo modal
        llamarModal(numComensales);

    }//GEN-LAST:event_clickComensal5

    private void radioComidaClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioComidaClick
        jRadioButtonCena.setSelected(false);
        jComboBoxCena.setEnabled(false);
        jComboBoxCena.setSelectedIndex(0);
        jComboBoxComida.setEnabled(true);
    }//GEN-LAST:event_radioComidaClick

    private void radioCenaClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCenaClick
        jRadioButtonComida.setSelected(false);
        jComboBoxComida.setEnabled(false);
        jComboBoxComida.setSelectedIndex(0);
        jComboBoxCena.setEnabled(true);
    }//GEN-LAST:event_radioCenaClick

    private void clickButtonBorrar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickButtonBorrar
        // Borrar campos
        jTextFieldNombre.setText("");
        jTextFieldTelefono.setText("");

        // Reactivar botón
        if (jButton1.isEnabled() == false) {
            jButton1.setEnabled(true);
        } else if (jButton2.isEnabled() == false) {
            jButton2.setEnabled(true);
        } else if (jButton3.isEnabled() == false) {
            jButton3.setEnabled(true);
        } else if (jButton4.isEnabled() == false) {
            jButton4.setEnabled(true);
        } else if (jButton5.isEnabled() == false) {
            jButton5.setEnabled(true);
        }

        // Borrar comensales
        borrarComensales();
        jTextAreaMenu.setText("");

        //Borrar horarios
        if (jRadioButtonComida.isSelected() == true) {
            jRadioButtonComida.setSelected(false);
            jComboBoxComida.setEnabled(false);
            jComboBoxComida.setSelectedIndex(0);
        } else {
            jRadioButtonCena.setSelected(false);
            jComboBoxCena.setEnabled(false);
            jComboBoxCena.setSelectedIndex(0);
        }

        // Borrar calendario
        jCalendarFecha.setCalendar(Calendar.getInstance());
    }//GEN-LAST:event_clickButtonBorrar

    private void clickButtonCancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickButtonCancelar

        // Borrar comensales
        borrarComensales();
        jTextAreaMenu.setText("");

        // Desactivar diálogo modal
        jDialogComensales.setVisible(false);

        // Reactivar botón
        if (jButton1.isEnabled() == false) {
            jButton1.setEnabled(true);
        } else if (jButton2.isEnabled() == false) {
            jButton2.setEnabled(true);
        } else if (jButton3.isEnabled() == false) {
            jButton3.setEnabled(true);
        } else if (jButton4.isEnabled() == false) {
            jButton4.setEnabled(true);
        } else if (jButton5.isEnabled() == false) {
            jButton5.setEnabled(true);
        }
    }//GEN-LAST:event_clickButtonCancelar

    private void clickButtonReservar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickButtonReservar

        // Estabecer semáforo
        boolean datosOK = true;

        // Comprobación de datos        
        if (jTextFieldNombre.getText().equals("") || jTextFieldTelefono.getText().equals("")) {
            JOptionPane.showMessageDialog(jPanelContenedor2, "Uno o más campos están vacios.", "Error", JOptionPane.ERROR_MESSAGE);
            datosOK = false;
        } else if (jRadioButtonComida.isSelected() == false && jRadioButtonCena.isSelected() == false) {
            JOptionPane.showMessageDialog(jPanelContenedor2, "Uno o más campos están vacios.", "Error", JOptionPane.ERROR_MESSAGE);
            datosOK = false;
        } else if (jComboBoxComida.isEnabled() == true && jComboBoxComida.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(jPanelContenedor2, "Por favor, seleccione la hora de reserva.", "Error", JOptionPane.ERROR_MESSAGE);
            datosOK = false;
        } else if (jComboBoxCena.isEnabled() == true && jComboBoxCena.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(jPanelContenedor2, "Por favor, seleccione la hora de reserva.", "Error", JOptionPane.ERROR_MESSAGE);
            datosOK = false;
        } else if (numComensales == -1) {
            JOptionPane.showMessageDialog(jPanelContenedor2, "Por favor, seleccione el número de comensales.", "Error", JOptionPane.ERROR_MESSAGE);
            datosOK = false;
        } else {
            try {
                Integer.valueOf(jTextFieldTelefono.getText());
            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(jPanelContenedor2, "Número de teléfono no valido.", "Error", JOptionPane.ERROR_MESSAGE);
                datosOK = false;
            }
        }

        if (datosOK == true) {
            // Obtención de los datos de los campos de texto
            String nomRes = jTextFieldNombre.getText();
            String numRes = jTextFieldTelefono.getText();

            // Obtención de los datos de las combo box
            String horario = "";
            String hora = "";

            if (jRadioButtonComida.isSelected()) {
                horario = "Comida";
                hora = (String) jComboBoxComida.getSelectedItem();
            } else if (jRadioButtonCena.isSelected()) {
                horario = "Cena";
                hora = (String) jComboBoxCena.getSelectedItem();
            }

            // Obtención de los datos del calendario
            Calendar fecha = jCalendarFecha.getCalendar();
            diaSem = fecha.get(Calendar.DAY_OF_WEEK);
            diaMes = fecha.get(Calendar.DAY_OF_MONTH);
            mes = fecha.get(Calendar.MONTH) + 1;
            any = fecha.get(Calendar.YEAR);

            // Mostrar aviso
            JOptionPane.showMessageDialog(jPanelContenedor2, "Su reserva se ha realizado correctamente." + "\n" + "(El archivo de texto ha sido guardado en la carpeta \"files\" del proyecto.", "¡Éxito!", JOptionPane.INFORMATION_MESSAGE);

            // Crear documento
            crearArchivoReserva(nomRes, numRes, horario, hora, fecha);
        }
    }//GEN-LAST:event_clickButtonReservar

    private void clickComensal6(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickComensal6
        msgInf();
    }//GEN-LAST:event_clickComensal6

    private void clickComensal7(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickComensal7
        msgInf();
    }//GEN-LAST:event_clickComensal7

    private void clickComensal8(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickComensal8
        msgInf();
    }//GEN-LAST:event_clickComensal8

    private void clickComensal9(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickComensal9
        msgInf();
    }//GEN-LAST:event_clickComensal9

    private void clickComensal10(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickComensal10
        msgInf();
    }//GEN-LAST:event_clickComensal10

    private void clickComensal11(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickComensal11
        msgInf();
    }//GEN-LAST:event_clickComensal11

    private void clickComensal12(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickComensal12
        msgInf();
    }//GEN-LAST:event_clickComensal12

    private void clickButtonAceptar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickButtonAceptar
        // Declaración de semáforo
        boolean comensalesOK = false;

        switch (numComensales) {
            case 1:
                if (jTextFieldC1.getText().equals("")) {
                    JOptionPane.showMessageDialog(jDialogComensales, "Uno o más campos están vacios.", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    // Obtener cadena de texto con todos los platos
                    String slcnC1 = jTextFieldC1.getText().trim().replace(" ", "");

                    // Separar los platos e incluirlos en un Array
                    arrayC1 = slcnC1.split(",");

                    // Comprobación del número de platos
                    if (arrayC1.length > 4) {
                        // Mensaje de error
                        JOptionPane.showMessageDialog(jDialogComensales, "Has seleccionado más de 4 platos.", "Error", JOptionPane.ERROR_MESSAGE);

                        // Borrar arrays
                        arrayC1 = null;
                    }
                    // Confirmación de selección
                    comensalesOK = true;
                }
                break;
            case 2:
                if (jTextFieldC1.getText().equals("") || jTextFieldC2.getText().equals("")) {
                    JOptionPane.showMessageDialog(jDialogComensales, "Uno o más campos están vacios.", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    // Obtener cadena de texto con todos los platos
                    String slcnC1 = jTextFieldC1.getText().trim().replace(" ", "");
                    String slcnC2 = jTextFieldC2.getText().trim().replace(" ", "");

                    // Separar los platos e incluirlos en un Array
                    arrayC1 = slcnC1.split(",");
                    arrayC2 = slcnC2.split(",");

                    // Comprobación del número de platos
                    if (arrayC1.length > 4 || arrayC2.length > 4) {
                        // Mensaje de error
                        JOptionPane.showMessageDialog(jDialogComensales, "Alguno de los comensales ha seleccionado más de 4 platos.", "Error", JOptionPane.ERROR_MESSAGE);

                        // Borrar arrays
                        arrayC1 = null;
                        arrayC2 = null;
                    }
                    // Confirmación de selección
                    comensalesOK = true;
                }
                break;
            case 3:
                if (jTextFieldC1.getText().equals("") || jTextFieldC2.getText().equals("") || jTextFieldC3.getText().equals("")) {
                    JOptionPane.showMessageDialog(jDialogComensales, "Uno o más campos están vacios.", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    // Obtener cadena de texto con todos los platos
                    String slcnC1 = jTextFieldC1.getText().trim().replace(" ", "");
                    String slcnC2 = jTextFieldC2.getText().trim().replace(" ", "");
                    String slcnC3 = jTextFieldC3.getText().trim().replace(" ", "");

                    // Separar los platos e incluirlos en un Array
                    arrayC1 = slcnC1.split(",");
                    arrayC2 = slcnC2.split(",");
                    arrayC3 = slcnC3.split(",");

                    // Comprobación del número de platos
                    if (arrayC1.length > 4 || arrayC2.length > 4 || arrayC3.length > 4) {
                        // Mensaje de error
                        JOptionPane.showMessageDialog(jDialogComensales, "Alguno de los comensales ha seleccionado más de 4 platos.", "Error", JOptionPane.ERROR_MESSAGE);

                        // Borrar arrays
                        arrayC1 = null;
                        arrayC2 = null;
                        arrayC3 = null;
                    }
                    // Confirmación de selección
                    comensalesOK = true;
                }
                break;
            case 4:
                if (jTextFieldC1.getText().equals("") || jTextFieldC2.getText().equals("") || jTextFieldC3.getText().equals("") || jTextFieldC4.getText().equals("")) {
                    JOptionPane.showMessageDialog(jDialogComensales, "Uno o más campos están vacios.", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    // Obtener cadena de texto con todos los platos
                    String slcnC1 = jTextFieldC1.getText().trim().replace(" ", "");
                    String slcnC2 = jTextFieldC2.getText().trim().replace(" ", "");
                    String slcnC3 = jTextFieldC3.getText().trim().replace(" ", "");
                    String slcnC4 = jTextFieldC4.getText().trim().replace(" ", "");

                    // Separar los platos e incluirlos en un Array
                    arrayC1 = slcnC1.split(",");
                    arrayC2 = slcnC2.split(",");
                    arrayC3 = slcnC3.split(",");
                    arrayC4 = slcnC4.split(",");

                    // Comprobación del número de platos
                    if (arrayC1.length > 4 || arrayC2.length > 4 || arrayC3.length > 4 || arrayC4.length > 4) {
                        // Mensaje de error
                        JOptionPane.showMessageDialog(jDialogComensales, "Alguno de los comensales ha seleccionado más de 4 platos.", "Error", JOptionPane.ERROR_MESSAGE);

                        // Borrar arrays
                        arrayC1 = null;
                        arrayC2 = null;
                        arrayC3 = null;
                        arrayC4 = null;
                    }
                    // Confirmación de selección
                    comensalesOK = true;
                }
                break;
            case 5:
                if (jTextFieldC1.getText().equals("") || jTextFieldC2.getText().equals("") || jTextFieldC3.getText().equals("") || jTextFieldC4.getText().equals("") || jTextFieldC5.getText().equals("")) {
                    JOptionPane.showMessageDialog(jDialogComensales, "Uno o más campos están vacios.", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    // Obtener cadena de texto con todos los platos
                    String slcnC1 = jTextFieldC1.getText().trim().replace(" ", "");
                    String slcnC2 = jTextFieldC2.getText().trim().replace(" ", "");
                    String slcnC3 = jTextFieldC3.getText().trim().replace(" ", "");
                    String slcnC4 = jTextFieldC4.getText().trim().replace(" ", "");
                    String slcnC5 = jTextFieldC5.getText().trim().replace(" ", "");

                    // Separar los platos e incluirlos en un array
                    arrayC1 = slcnC1.split(",");
                    arrayC2 = slcnC2.split(",");
                    arrayC3 = slcnC3.split(",");
                    arrayC4 = slcnC4.split(",");
                    arrayC5 = slcnC5.split(",");

                    // Comprobación del número de platos
                    if (arrayC1.length > 4 || arrayC2.length > 4 || arrayC3.length > 4 || arrayC4.length > 4 || arrayC5.length > 4) {
                        // Mensaje de error
                        JOptionPane.showMessageDialog(jDialogComensales, "Alguno de los comensales ha seleccionado más de 4 platos.", "Error", JOptionPane.ERROR_MESSAGE);

                        // Borrar arrays
                        arrayC1 = null;
                        arrayC2 = null;
                        arrayC3 = null;
                        arrayC4 = null;
                        arrayC5 = null;
                    }
                    // Confirmación de selección
                    comensalesOK = true;
                }
                break;
        }
        if (comensalesOK == true) {
            //Mostrar mensaje
            JOptionPane.showMessageDialog(jDialogComensales, "La selección de platos ha sido guardada correctamente.", "Menú", JOptionPane.INFORMATION_MESSAGE);
            // Desactivar diálogo modal
            jDialogComensales.setVisible(false);
        }
    }//GEN-LAST:event_clickButtonAceptar

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonReservar;
    private com.toedter.calendar.JCalendar jCalendarFecha;
    private javax.swing.JComboBox<String> jComboBoxCena;
    private javax.swing.JComboBox<String> jComboBoxComida;
    private javax.swing.JDialog jDialogComensales;
    private javax.swing.JLabel jLabelC1;
    private javax.swing.JLabel jLabelC2;
    private javax.swing.JLabel jLabelC3;
    private javax.swing.JLabel jLabelC4;
    private javax.swing.JLabel jLabelC5;
    private javax.swing.JLabel jLabelComensales;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNomRes;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumCom;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JPanel jPanelBarra2;
    private javax.swing.JPanel jPanelBarra3;
    private javax.swing.JPanel jPanelBorde;
    private javax.swing.JPanel jPanelComensales;
    private javax.swing.JPanel jPanelContenedor2;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelModal;
    private javax.swing.JPanel jPanelReserva;
    private javax.swing.JPanel jPanelTextBox;
    private javax.swing.JPanel jPanelTextBox1;
    private javax.swing.JRadioButton jRadioButtonCena;
    private javax.swing.JRadioButton jRadioButtonComida;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaMenu;
    private javax.swing.JTextField jTextFieldC1;
    private javax.swing.JTextField jTextFieldC2;
    private javax.swing.JTextField jTextFieldC3;
    private javax.swing.JTextField jTextFieldC4;
    private javax.swing.JTextField jTextFieldC5;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables

    // Métodos
    private final void llamarModal(int numComensales) {
        // Manejar botones funcionales
        switch (numComensales) {
            case 1:
                // Botón 1 pulsado
                jButton1.setEnabled(false);
                jLabelNumCom.setText(String.format("Número de comensales seleccionado: %d - Seleccione los platos para cada comensal (Máximo 4)", numComensales));

                // Activar etiquetas
                jLabelC1.setEnabled(true);

                // Activar campos
                jTextFieldC1.setEnabled(true);
                break;
            case 2:
                // Botón 2 pulsado
                jButton2.setEnabled(false);
                jLabelNumCom.setText(String.format("Número de comensales seleccionado: %d - Seleccione los platos para cada comensal (Máximo 4)", numComensales));

                // Activar etiquetas
                jLabelC1.setEnabled(true);
                jLabelC2.setEnabled(true);

                // Activar campos
                jTextFieldC1.setEnabled(true);
                jTextFieldC2.setEnabled(true);
                break;
            case 3:
                // Botón 3 pulsado
                jButton3.setEnabled(false);
                jLabelNumCom.setText(String.format("Número de comensales seleccionado: %d - Seleccione los platos para cada comensal (Máximo 4)", numComensales));

                // Activar etiquetas
                jLabelC1.setEnabled(true);
                jLabelC2.setEnabled(true);
                jLabelC3.setEnabled(true);

                // Activar campos
                jTextFieldC1.setEnabled(true);
                jTextFieldC2.setEnabled(true);
                jTextFieldC3.setEnabled(true);
                break;
            case 4:
                // Botón 4 pulsado
                jButton4.setEnabled(false);
                jLabelNumCom.setText(String.format("Número de comensales seleccionado: %d - Seleccione los platos para cada comensal (Máximo 4)", numComensales));

                // Activar etiquetas
                jLabelC1.setEnabled(true);
                jLabelC2.setEnabled(true);
                jLabelC3.setEnabled(true);
                jLabelC4.setEnabled(true);

                // Activar campos
                jTextFieldC1.setEnabled(true);
                jTextFieldC2.setEnabled(true);
                jTextFieldC3.setEnabled(true);
                jTextFieldC4.setEnabled(true);
                break;
            case 5:
                // Botón 5 pulsado
                jButton5.setEnabled(false);
                jLabelNumCom.setText(String.format("Número de comensales seleccionado: %d - Seleccione los platos para cada comensal (Máximo 4)", numComensales));

                // Activar etiquetas
                jLabelC1.setEnabled(true);
                jLabelC2.setEnabled(true);
                jLabelC3.setEnabled(true);
                jLabelC4.setEnabled(true);
                jLabelC5.setEnabled(true);

                // Activar campos
                jTextFieldC1.setEnabled(true);
                jTextFieldC2.setEnabled(true);
                jTextFieldC3.setEnabled(true);
                jTextFieldC4.setEnabled(true);
                jTextFieldC5.setEnabled(true);
                break;
            default:
                JOptionPane.showMessageDialog(jDialogComensales, "Ha ocurrido un error inesperado.", "Error", JOptionPane.ERROR_MESSAGE);
                break;
        }

        // Leer menú
        ArrayList<String> lineas = leerArchivo();

        for (String linea : lineas) {
            jTextAreaMenu.append(linea + "\n");
        }

        // Mostrar diálogo modal
        jDialogComensales.setVisible(true);

    }

    private void msgInf() {
        JOptionPane.showMessageDialog(jPanelContenedor2, "El programador está durmiendo. Por favor, inténtelo más tarde.", "Vaya...", JOptionPane.INFORMATION_MESSAGE);
    }

    private static ArrayList<String> leerArchivo() {
        ArrayList<String> lineas = new ArrayList<>();

        try {
            FileReader fr = new FileReader("files\\menu.txt");
            BufferedReader br = new BufferedReader(fr);

            String s = br.readLine();

            while (s != null) {
                lineas.add(s);
                s = br.readLine();
            }
            fr.close();

        } catch (FileNotFoundException fnfe) {
            System.out.println("No se ha encontrado el archivo datos.txt\n" + fnfe.toString());
        } catch (IOException ioe) {
            System.out.println("No se ha podido acceder al archivo datos.txt\n" + ioe.toString());
        }
        return lineas;
    }

    private void borrarComensales() {

        // Reiniciar comensales
        numComensales = -1;
        
        // Desactivar etiquetas
        jLabelC1.setEnabled(false);
        jLabelC2.setEnabled(false);
        jLabelC3.setEnabled(false);
        jLabelC4.setEnabled(false);
        jLabelC5.setEnabled(false);

        // Vaciar campos
        jTextFieldC1.setText("");
        jTextFieldC2.setText("");
        jTextFieldC3.setText("");
        jTextFieldC4.setText("");
        jTextFieldC5.setText("");

        // Desactivar campos
        jTextFieldC1.setEnabled(false);
        jTextFieldC2.setEnabled(false);
        jTextFieldC3.setEnabled(false);
        jTextFieldC4.setEnabled(false);
        jTextFieldC5.setEnabled(false);

        // Borrar arrays
        arrayC1 = null;
        arrayC2 = null;
        arrayC3 = null;
        arrayC4 = null;

        // Borrar Menú
        jTextAreaMenu.setText("");

    }

    public void crearArchivoReserva(String nomRes, String numRes, String horario, String hora, Calendar fecha) {
        try {
            String separador = "---";
            String contenido = "";
            String pedido1;
            String pedido2;
            String pedido3;
            String pedido4;
            String pedido5;

            if (numComensales == 1) {
                pedido1 = String.join(",", arrayC1);

                contenido
                        = "FECHA DE RESERVA\n"
                        + "================\n"
                        + "Nombre de la persona: " + nomRes + "\n"
                        + "Número telefónico: " + numRes + "\n"
                        + "Número de comensales: " + numComensales + "\n"
                        + "Horario de reserva: " + horario + "\n"
                        + "Hora de reserva: " + hora + "\n"
                        + "Fecha de reserva: " + diaMes + " del " + mes + " del " + any + "\n"
                        + separador + "\n"
                        + "Pedido del primer comensal: " + pedido1 + "\n"
                        + separador + "\n"
                        + "¡Gracias por reservar!\n";
            } else if (numComensales == 2) {
                pedido1 = String.join(",", arrayC1);
                pedido2 = String.join(",", arrayC2);

                contenido
                        = "FECHA DE RESERVA\n"
                        + "================\n"
                        + "Nombre de la persona: " + nomRes + "\n"
                        + "Número telefónico: " + numRes + "\n"
                        + "Número de comensales: " + numComensales + "\n"
                        + "Horario de reserva: " + horario + "\n"
                        + "Hora de reserva: " + hora + "\n"
                        + "Fecha de reserva: " + diaMes + " del " + mes + " del " + any + "\n"
                        + separador + "\n"
                        + "Pedido del primer comensal: " + pedido1 + "\n"
                        + separador + "\n"
                        + "Pedido del segundo comensal: " + pedido2 + "\n"
                        + separador + "\n"
                        + "¡Gracias por reservar!\n";
            } else if (numComensales == 3) {
                pedido1 = String.join(",", arrayC1);
                pedido2 = String.join(",", arrayC2);
                pedido3 = String.join(",", arrayC3);

                contenido
                        = "FECHA DE RESERVA\n"
                        + "================\n"
                        + "Nombre de la persona: " + nomRes + "\n"
                        + "Número telefónico: " + numRes + "\n"
                        + "Número de comensales: " + numComensales + "\n"
                        + "Horario de reserva: " + horario + "\n"
                        + "Hora de reserva: " + hora + "\n"
                        + "Fecha de reserva: " + diaMes + " del " + mes + " del " + any + "\n"
                        + separador + "\n"
                        + "Pedido del primer comensal: " + pedido1 + "\n"
                        + separador + "\n"
                        + "Pedido del segundo comensal: " + pedido2 + "\n"
                        + separador + "\n"
                        + "Pedido del tercer comensal: " + pedido3 + "\n"
                        + separador + "\n"
                        + "¡Gracias por reservar!\n";
            } else if (numComensales == 4) {
                pedido1 = String.join(",", arrayC1);
                pedido2 = String.join(",", arrayC2);
                pedido3 = String.join(",", arrayC3);
                pedido4 = String.join(",", arrayC4);

                contenido
                        = "FECHA DE RESERVA\n"
                        + "================\n"
                        + "Nombre de la persona: " + nomRes + "\n"
                        + "Número telefónico: " + numRes + "\n"
                        + "Número de comensales: " + numComensales + "\n"
                        + "Horario de reserva: " + horario + "\n"
                        + "Hora de reserva: " + hora + "\n"
                        + "Fecha de reserva: " + "Fecha de reserva: " + diaMes + " del " + mes + " del " + any + "\n"
                        + separador + "\n"
                        + "Pedido del primer comensal: " + pedido1 + "\n"
                        + separador + "\n"
                        + "Pedido del segundo comensal: " + pedido2 + "\n"
                        + separador + "\n"
                        + "Pedido del tercer comensal: " + pedido3 + "\n"
                        + separador + "\n"
                        + "Pedido del cuarto comensal: " + pedido4 + "\n"
                        + separador + "\n"
                        + "¡Gracias por reservar!\n";
            } else if (numComensales == 5) {
                pedido1 = String.join(",", arrayC1);
                pedido2 = String.join(",", arrayC2);
                pedido3 = String.join(",", arrayC3);
                pedido4 = String.join(",", arrayC4);
                pedido5 = String.join(",", arrayC5);

                contenido
                        = "FECHA DE RESERVA\n"
                        + "================\n"
                        + "Nombre de la persona: " + nomRes + "\n"
                        + "Número telefónico: " + numRes + "\n"
                        + "Número de comensales: " + numComensales + "\n"
                        + "Horario de reserva: " + horario + "\n"
                        + "Hora de reserva: " + hora + "\n"
                        + "Fecha de reserva: " + "Fecha de reserva: " + diaMes + " del " + mes + " del " + any + "\n"
                        + separador + "\n"
                        + "Pedido del primer comensal: " + pedido1 + "\n"
                        + separador + "\n"
                        + "Pedido del segundo comensal: " + pedido2 + "\n"
                        + separador + "\n"
                        + "Pedido del tercer comensal: " + pedido3 + "\n"
                        + separador + "\n"
                        + "Pedido del cuarto comensal: " + pedido4 + "\n"
                        + separador + "\n"
                        + "Pedido del quinto comensal: " + pedido5 + "\n"
                        + separador + "\n"
                        + "¡Gracias por reservar!\n";
            }

            // Abrir buffer
            BufferedWriter writer = new BufferedWriter(new FileWriter("files\\reserva.txt"));
            writer.write(contenido);

            // Cerrar buffer
            writer.close();

        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
